### PR TITLE
ENH: Add code format GitHub action workflow

### PR DESCRIPTION
**Pull request by jhlegarreta**
Add code format GitHub action workflow.

Add the corresponding configuration file.

Add the corresponding badges to the `README` file.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
@felixdumais So OK if I merge this and we'll fix the formatting issues in a separate PR ?

**Comment by jhlegarreta** [comment]
Depends on PR #33.

**Comment by jhlegarreta** [comment]
This is ready @felixdumais.

I'd push a subsequent PR where I locally apply the formatting.

**Review by felixdumais — APPROVED** [review]

**Comment by jhlegarreta** [comment]
> I'd push a subsequent PR where I locally apply the formatting.

PR #42.

**Pull request merged**
